import { normalizeTeamName } from "./team-normalization";
import type { BetType, ClassificationStatus } from "./types";

export type GammaMarketTeam = { name?: string | null; ordering?: string | null };
export type GammaMarketEvent = { sport?: { sport?: string | null } | null; teams?: GammaMarketTeam[] | null };
export type GammaMarket = {
  slug: string | null;
  question: string | null;
  groupItemTitle: string | null;
  /** Structured bet-type field as returned by gamma-api, e.g. "moneyline" | "spreads" | "totals" | "player_prop" | "futures". */
  sportsMarketType: string | null;
  line: number | null;
  events: GammaMarketEvent[] | null;
};

export type EligibleReasonCode = "ELIGIBLE_FULL_GAME_MONEYLINE" | "ELIGIBLE_FULL_GAME_SPREAD" | "ELIGIBLE_FULL_GAME_TOTAL";

export type RejectReasonCode =
  | "REJECT_NON_MLB"
  | "REJECT_PROP"
  | "REJECT_F5"
  | "REJECT_INNING"
  | "REJECT_FUTURE"
  | "REJECT_PARLAY"
  | "REJECT_ESPORTS"
  | "REJECT_EXOTIC"
  | "REJECT_TEAM_TOTAL"
  | "REJECT_UNSUPPORTED_MARKET_TYPE";

export type UnverifiedReasonCode =
  | "UNVERIFIED_METADATA_MISSING"
  | "UNVERIFIED_AMBIGUOUS_PERIOD"
  | "UNVERIFIED_PARSE_FAILURE"
  | "UNVERIFIED_CONFLICTING_METADATA"
  | "UNVERIFIED_UNKNOWN_TEAM"
  | "UNVERIFIED_MISSING_LINE"
  | "UNVERIFIED_FETCH_FAILED"
  | "UNVERIFIED_EMPTY_RESPONSE"
  | "UNVERIFIED_MALFORMED_RESPONSE";

export type ReasonCode = EligibleReasonCode | RejectReasonCode | UnverifiedReasonCode;

export type UnverifiedDisposition = "RETRYABLE" | "TERMINAL";

/**
 * ============================== TASK 12F / P1-H: RETRYABLE VS TERMINAL UNVERIFIED ==============================
 * ROOT CAUSE (Codex P1 finding): source-poll.server.ts's downstream-retry loop treated
 * EVERY UNVERIFIED classification identically -- stays PENDING forever. That is correct
 * for a genuinely transient result, but classifyGammaMarket's own semantic UNVERIFIED
 * reasons (below) are deterministic given a successfully-read Gamma response for that
 * exact, immutable conditionId -- retrying reproduces the identical result forever.
 * Enough old permanently-UNVERIFIED fills can occupy the entire bounded
 * findPendingDownstreamFills batch, starving genuinely newer/retryable fills.
 *
 * RETRYABLE -- generated by fetchSourceMarketMetadata's OWN network/response-availability
 * wrapper, BEFORE classifyGammaMarket ever runs (see source-metadata.server.ts's
 * unverifiedResult calls: HTTP failure, empty gamma-api response, malformed JSON). These
 * mean "we failed to obtain a trustworthy response this attempt" -- genuinely transient;
 * a later poll may succeed. Must stay PENDING.
 *
 * TERMINAL -- returned by classifyGammaMarket itself AFTER a successfully-parsed, readable
 * Gamma response. Every one of these reflects a deterministic property of that exact
 * conditionId's own immutable market record (its team names, its slug, its structured
 * fields) -- retrying reproduces the identical UNVERIFIED result forever, so retaining it
 * as PENDING serves no purpose except permanently occupying retry capacity. Recorded as
 * TERMINAL_UNVERIFIED downstream evidence (see the Task 12F/P1-H migration) -- NOT
 * collapsed into TERMINAL_INELIGIBLE, since "we could not verify eligibility" and "we
 * positively determined ineligibility" remain distinct, durably auditable outcomes.
 *
 * Exhaustive over the real UnverifiedReasonCode union -- a reason code added to that type
 * without updating this switch is a TypeScript compile error, not a silent default.
 * ================================================================================
 */
export function classifyUnverifiedDisposition(reasonCode: UnverifiedReasonCode): UnverifiedDisposition {
  switch (reasonCode) {
    case "UNVERIFIED_FETCH_FAILED":
    case "UNVERIFIED_EMPTY_RESPONSE":
    case "UNVERIFIED_MALFORMED_RESPONSE":
      return "RETRYABLE";
    case "UNVERIFIED_METADATA_MISSING":
    case "UNVERIFIED_AMBIGUOUS_PERIOD":
    case "UNVERIFIED_PARSE_FAILURE":
    case "UNVERIFIED_CONFLICTING_METADATA":
    case "UNVERIFIED_UNKNOWN_TEAM":
    case "UNVERIFIED_MISSING_LINE":
      return "TERMINAL";
  }
}

export type ClassificationResult = {
  status: ClassificationStatus;
  betType: BetType | null;
  line: number | null;
  awayTeam: string | null;
  homeTeam: string | null;
  reasonCode: ReasonCode;
  reason: string;
};

const ESPORTS_LEAGUES = new Set(["esports", "lol", "league of legends", "valorant", "cs", "csgo", "cs2", "dota", "dota2"]);

// Positive-exclusion text patterns. Scanned across question + slug + groupItemTitle together so a
// signal in ANY structured text field is enough to reject — the mission requires excluding rather
// than guessing when any one field indicates a non-full-game structure.
const F5_PATTERN = /first\s*5\b|first\s*five|\bf5\b|1st\s*5\b|5\s*innings/i;
const ORDINAL_INNING_PATTERN = /\b(1st|first|2nd|second|3rd|third)\s+inning\b/i;
const PARTIAL_INNING_COUNT_PATTERN = /\bfirst\s*(3|7)\b/i;
// Broader than the specific patterns above: signals a partial-period market whose exact shape we
// can't pin down structurally. Checked only after the specific patterns above have had a chance to
// match, so it acts as a conservative catch-all rather than a false trigger on "5 innings" text
// that F5_PATTERN already claims.
const AMBIGUOUS_PERIOD_PATTERN = /\bthrough\s*\d+\s*innings?\b|\b\d+\s*innings?\b/i;
const PROP_PATTERN = /\bhome\s*runs?\b|\bhr\b|\bstrikeouts?\b|\bhits?\b|\brbis?\b|\btotal\s*bases\b|\bplayer\s*prop\b/i;
const FUTURE_PATTERN =
  /\bworld\s*series\s*champion\b|\bseries\s*winner\b|\bfutures?\b|\bchampion(ship)?\b|\bto\s*win\s*the\s*(world\s*series|division|pennant)\b|\bseason\s*win\s*total\b/i;
const PARLAY_PATTERN = /\bparlay\b|\bcombo\b|\bcombination\s*bet\b/i;
const EXOTIC_PATTERN = /\bexact\s*score\b|\balternate\b/i;
const TEAM_TOTAL_PATTERN = /\bteam\s*total\b/i;

const SPORTS_MARKET_TYPE_TO_BET_TYPE: Record<string, BetType> = {
  moneyline: "MONEYLINE",
  spreads: "SPREAD",
  totals: "TOTAL",
};

function combinedText(market: GammaMarket): string {
  return `${market.question ?? ""} ${market.slug ?? ""} ${market.groupItemTitle ?? ""}`;
}

function eligible(betType: BetType, line: number | null, awayTeam: string, homeTeam: string): ClassificationResult {
  const reasonCode: EligibleReasonCode =
    betType === "MONEYLINE" ? "ELIGIBLE_FULL_GAME_MONEYLINE" : betType === "SPREAD" ? "ELIGIBLE_FULL_GAME_SPREAD" : "ELIGIBLE_FULL_GAME_TOTAL";
  return {
    status: "ELIGIBLE",
    betType,
    line: betType === "MONEYLINE" ? null : line,
    awayTeam,
    homeTeam,
    reasonCode,
    reason: `full-game MLB ${betType.toLowerCase()}`,
  };
}

function rejected(reasonCode: RejectReasonCode, reason: string): ClassificationResult {
  return { status: "INELIGIBLE", betType: null, line: null, awayTeam: null, homeTeam: null, reasonCode, reason };
}

function unverified(reasonCode: UnverifiedReasonCode, reason: string): ClassificationResult {
  return { status: "UNVERIFIED", betType: null, line: null, awayTeam: null, homeTeam: null, reasonCode, reason };
}

/** Parses a gamma/PM-US-style line token like "1pt5" or "7pt5" into a magnitude, e.g. 1.5 / 7.5. Sign is never encoded in the slug. */
function parseLineToken(token: string | undefined | null): number | null {
  if (!token) return null;
  const m = token.match(/^(\d+)pt(\d+)$/i);
  if (!m) return null;
  return Number(`${m[1]}.${m[2]}`);
}

/** Conservative slug fallback, used only when sportsMarketType is entirely absent. */
function parseBetTypeFromSlug(slug: string): { betType: BetType; line: number | null } | null {
  const spreadMatch = slug.match(/-spread-(?:home|away)-(\d+pt\d+)/i);
  if (spreadMatch) return { betType: "SPREAD", line: parseLineToken(spreadMatch[1]) };
  const totalMatch = slug.match(/-total-(\d+pt\d+)/i);
  if (totalMatch) return { betType: "TOTAL", line: parseLineToken(totalMatch[1]) };
  if (/^mlb-[a-z0-9]+-[a-z0-9]+-\d{4}-\d{2}-\d{2}$/i.test(slug)) return { betType: "MONEYLINE", line: null };
  return null;
}

/** Extracts the slug-encoded line magnitude for the given bet type, for conflict-checking against the structured `line` field. */
function parseLineFromSlugForConflictCheck(slug: string, betType: BetType): number | null {
  if (betType === "SPREAD") return parseLineToken(slug.match(/-spread-(?:home|away)-(\d+pt\d+)/i)?.[1]);
  if (betType === "TOTAL") return parseLineToken(slug.match(/-total-(\d+pt\d+)/i)?.[1]);
  return null;
}

/** Extracts away/home team tokens from a well-formed `mlb-<away>-<home>-YYYY-MM-DD...` slug, for team-identity conflict checking. */
function parseTeamTokensFromSlug(slug: string): { away: string; home: string } | null {
  const m = slug.match(/^mlb-([a-z0-9]+)-([a-z0-9]+)-\d{4}-\d{2}-\d{2}/i);
  if (!m || !m[1] || !m[2]) return null;
  return { away: m[1], home: m[2] };
}

/**
 * Pure classifier: given one gamma-api market shape, decides ELIGIBLE / INELIGIBLE / UNVERIFIED
 * for Phase-1 MLB full-game moneyline/spread/total. Fails closed — any ambiguity becomes
 * UNVERIFIED rather than ELIGIBLE. Structured fields are authoritative when present; slug/text is
 * used only as a conservative fallback or as an independent cross-check that can downgrade a
 * structured-looking market to UNVERIFIED_CONFLICTING_METADATA when the two disagree.
 */
export function classifyGammaMarket(market: GammaMarket): ClassificationResult {
  const text = combinedText(market);

  // 1. League.
  const structuredLeague = market.events?.[0]?.sport?.sport?.toLowerCase() ?? null;
  if (structuredLeague !== null) {
    if (structuredLeague !== "mlb") {
      if (ESPORTS_LEAGUES.has(structuredLeague)) return rejected("REJECT_ESPORTS", `league is ${structuredLeague}, an esports league`);
      return rejected("REJECT_NON_MLB", `league is ${structuredLeague}, not mlb`);
    }
  } else {
    const slugLooksLikeMlb = /^mlb-/i.test(market.slug ?? "");
    if (!slugLooksLikeMlb) return unverified("UNVERIFIED_METADATA_MISSING", "no structured league and slug does not indicate MLB");
    // else: proceed, league tentatively confirmed via conservative slug prefix.
  }

  // 2. Positive exclusion text patterns — checked before bet-type resolution so text evidence can
  //    override a structurally full-game-looking sportsMarketType/slug (mission's "structured
  //    priority" requirement cuts both ways: a period/prop/futures/parlay signal always wins).
  if (F5_PATTERN.test(text)) return rejected("REJECT_F5", "first-five-innings market excluded");
  if (ORDINAL_INNING_PATTERN.test(text) || PARTIAL_INNING_COUNT_PATTERN.test(text)) return rejected("REJECT_INNING", "single-inning/partial-inning market excluded");
  if (PROP_PATTERN.test(text)) return rejected("REJECT_PROP", "player prop market excluded");
  if (FUTURE_PATTERN.test(text) || market.sportsMarketType === "futures") return rejected("REJECT_FUTURE", "futures/series market excluded");
  if (PARLAY_PATTERN.test(text) || market.sportsMarketType === "parlay") return rejected("REJECT_PARLAY", "parlay/combo market excluded");
  if (EXOTIC_PATTERN.test(text)) return rejected("REJECT_EXOTIC", "exotic/alternate derivative market excluded");
  if (TEAM_TOTAL_PATTERN.test(text) || market.sportsMarketType === "team_total") return rejected("REJECT_TEAM_TOTAL", "team total market excluded (Phase 1 does not support it)");
  if (AMBIGUOUS_PERIOD_PATTERN.test(text)) return unverified("UNVERIFIED_AMBIGUOUS_PERIOD", "text references a partial-innings period that cannot be conclusively classified");

  // 3. Bet type: structured sportsMarketType first, conservative slug fallback second.
  let betType: BetType | undefined = market.sportsMarketType ? SPORTS_MARKET_TYPE_TO_BET_TYPE[market.sportsMarketType] : undefined;
  let fallbackLine: number | null = null;
  if (!betType) {
    if (market.sportsMarketType) {
      return rejected("REJECT_UNSUPPORTED_MARKET_TYPE", `sportsMarketType '${market.sportsMarketType}' is not an eligible full-game bet type`);
    }
    if (!market.slug) return unverified("UNVERIFIED_METADATA_MISSING", "no sportsMarketType and no slug to fall back on");
    const fallback = parseBetTypeFromSlug(market.slug);
    if (!fallback) return unverified("UNVERIFIED_PARSE_FAILURE", `slug '${market.slug}' did not match any known MLB market pattern`);
    betType = fallback.betType;
    fallbackLine = fallback.line;
  }

  // 4. Line requirement for SPREAD/TOTAL.
  let line = market.line ?? fallbackLine;
  if (betType !== "MONEYLINE" && line == null) {
    return unverified("UNVERIFIED_MISSING_LINE", `${betType} market has no numeric line available from any source`);
  }

  // 5. Structured-vs-slug line conflict (magnitude only — slugs never encode a sign).
  if (market.line != null && market.slug && betType !== "MONEYLINE") {
    const slugLine = parseLineFromSlugForConflictCheck(market.slug, betType);
    if (slugLine != null && Math.abs(Math.abs(market.line) - slugLine) > 0.01) {
      return unverified("UNVERIFIED_CONFLICTING_METADATA", `structured line ${market.line} conflicts with slug-derived line ${slugLine}`);
    }
  }

  // 6. Team identity + normalization ("selected side is understandable").
  const teams = market.events?.[0]?.teams ?? [];
  const awayRaw = teams.find((t) => t.ordering === "away")?.name ?? null;
  const homeRaw = teams.find((t) => t.ordering === "home")?.name ?? null;
  const awayCode = normalizeTeamName(awayRaw);
  const homeCode = normalizeTeamName(homeRaw);
  if (!awayCode || !homeCode) {
    return unverified("UNVERIFIED_UNKNOWN_TEAM", "one or both teams could not be normalized to a canonical MLB code");
  }

  // 7. Structured-vs-slug team-identity conflict.
  if (market.slug) {
    const slugTeams = parseTeamTokensFromSlug(market.slug);
    if (slugTeams) {
      const slugAwayCode = normalizeTeamName(slugTeams.away);
      const slugHomeCode = normalizeTeamName(slugTeams.home);
      if (slugAwayCode && slugHomeCode && (slugAwayCode !== awayCode || slugHomeCode !== homeCode)) {
        return unverified(
          "UNVERIFIED_CONFLICTING_METADATA",
          `structured teams ${awayCode}@${homeCode} conflict with slug-derived teams ${slugAwayCode}@${slugHomeCode}`,
        );
      }
    }
  }

  return eligible(betType, line, awayCode, homeCode);
}
