/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SportsShadowRouteImport } from './routes/sports-shadow'
import { Route as ApiPublicHooksIngestRouteImport } from './routes/api/public/hooks/ingest'
import { Route as ApiPublicHooksSportsShadowRouteImport } from './routes/api/public/hooks/sports-shadow'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsShadowRoute = SportsShadowRouteImport.update({
  id: '/sports-shadow',
  path: '/sports-shadow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIngestRoute = ApiPublicHooksIngestRouteImport.update({
  id: '/api/public/hooks/ingest',
  path: '/api/public/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSportsShadowRoute =
  ApiPublicHooksSportsShadowRouteImport.update({
    id: '/api/public/hooks/sports-shadow',
    path: '/api/public/hooks/sports-shadow',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sports-shadow': typeof SportsShadowRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/hooks/sports-shadow': typeof ApiPublicHooksSportsShadowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sports-shadow': typeof SportsShadowRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/hooks/sports-shadow': typeof ApiPublicHooksSportsShadowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sports-shadow': typeof SportsShadowRoute
  '/api/public/hooks/ingest': typeof ApiPublicHooksIngestRoute
  '/api/public/hooks/sports-shadow': typeof ApiPublicHooksSportsShadowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sports-shadow'
    | '/api/public/hooks/ingest'
    | '/api/public/hooks/sports-shadow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sports-shadow'
    | '/api/public/hooks/ingest'
    | '/api/public/hooks/sports-shadow'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/sports-shadow'
    | '/api/public/hooks/ingest'
    | '/api/public/hooks/sports-shadow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  SportsShadowRoute: typeof SportsShadowRoute
  ApiPublicHooksIngestRoute: typeof ApiPublicHooksIngestRoute
  ApiPublicHooksSportsShadowRoute: typeof ApiPublicHooksSportsShadowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports-shadow': {
      id: '/sports-shadow'
      path: '/sports-shadow'
      fullPath: '/sports-shadow'
      preLoaderRoute: typeof SportsShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ingest': {
      id: '/api/public/hooks/ingest'
      path: '/api/public/hooks/ingest'
      fullPath: '/api/public/hooks/ingest'
      preLoaderRoute: typeof ApiPublicHooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sports-shadow': {
      id: '/api/public/hooks/sports-shadow'
      path: '/api/public/hooks/sports-shadow'
      fullPath: '/api/public/hooks/sports-shadow'
      preLoaderRoute: typeof ApiPublicHooksSportsShadowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  SportsShadowRoute: SportsShadowRoute,
  ApiPublicHooksIngestRoute: ApiPublicHooksIngestRoute,
  ApiPublicHooksSportsShadowRoute: ApiPublicHooksSportsShadowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
